export enum InternalRouteEnum {
    apoptosize = 'apoptosize',
    binary_broadcast_state = 'binary/broadcast_state',
    binary_send_cachedAppData = 'binary/send_cachedAppData',
    binary_get_account_data_with_queue_hints = 'binary/get_account_data_with_queue_hints',
    binary_get_account_queue_count = 'binary/get_account_queue_count',
    binary_get_account_data_by_list = 'binary/get_account_data_by_list',
    binary_broadcast_finalstate = 'binary/broadcast_finalstate',
    binary_get_account_data = 'binary/get_account_data',
    binary_sync_trie_hashes = 'binary/sync_trie_hashes',
    binary_compare_cert = 'binary/compare_cert',
    binary_get_tx_timestamp = 'binary/get_tx_timestamp',
    binary_get_trie_hashes = 'binary/get_trie_hashes',
    binary_get_account_data_by_hashes = 'binary/get_account_data_by_hashes',
    binary_spread_tx_to_group_syncing = 'binary/spread_tx_to_group_syncing',
    binary_request_state_for_tx_post = 'binary/request_state_for_tx_post',
    binary_make_receipt = 'binary/make_receipt',
    binary_spread_appliedVoteHash = 'binary/spread_applied_vote_hash',
    binary_get_globalaccountreport = 'binary/get_globalaccountreport',
    binary_get_confirm_or_challenge = 'binary/get_confirm_or_challenge',
    binary_sign_app_data = 'binary/sign_app_data',
    binary_get_trie_account_hashes = 'binary/get_trie_account_hashes',
    binary_get_cached_app_data = 'binary/get_cached_app_data',
    binary_request_tx_and_state = 'binary/request_tx_and_state',
    binary_request_tx_and_state_before = 'binary/request_tx_and_state_before',
    binary_lost_archiver_investigate = 'binary/lost_archiver_investigate',
    binary_request_state_for_tx = 'binary/request_state_for_tx',
    binary_request_receipt_for_tx = 'binary/request_receipt_for_tx',
    binary_get_applied_vote = 'binary/get_applied_vote',
    binary_lost_report = 'binary/lost_report',
    binary_gossip = 'binary/gossip',
    binary_repair_oos_accounts = 'binary/repair_oos_accounts',
    binary_poqo_send_receipt = 'binary/poqo_send_receipt',
    binary_poqo_data_and_receipt = 'binary/poqo_data_and_receipt',
    binary_poqo_send_vote = 'binary/poqo_send_vote'
}
const askRoutes = new Set([
    InternalRouteEnum.apoptosize,
    InternalRouteEnum.binary_get_account_data_with_queue_hints,
    InternalRouteEnum.binary_get_account_queue_count,
    InternalRouteEnum.binary_get_account_data_by_list,
    InternalRouteEnum.binary_get_account_data,
    InternalRouteEnum.binary_compare_cert,
    InternalRouteEnum.binary_get_tx_timestamp,
    InternalRouteEnum.binary_get_trie_hashes,
    InternalRouteEnum.binary_get_account_data_by_hashes,
    InternalRouteEnum.binary_request_state_for_tx_post,
    InternalRouteEnum.binary_get_globalaccountreport,
    InternalRouteEnum.binary_get_confirm_or_challenge,
    InternalRouteEnum.binary_sign_app_data,
    InternalRouteEnum.binary_get_trie_account_hashes,
    InternalRouteEnum.binary_get_cached_app_data,
    InternalRouteEnum.binary_request_tx_and_state,
    InternalRouteEnum.binary_request_state_for_tx,
    InternalRouteEnum.binary_request_receipt_for_tx,
    InternalRouteEnum.binary_get_applied_vote,
]);
export function isAskRoute(route: string): boolean {
    return askRoutes.has(route as InternalRouteEnum);
}
export function isTellRoute(route: string): boolean {
    return !isAskRoute(route) || route === InternalRouteEnum.apoptosize;
}