import { StrictLogsConfiguration } from '../shardus/shardus-types'

const LOGS_CONFIG: StrictLogsConfiguration = {
  saveConsoleOutput: true,
  dir: 'logs',
  files: { main: '', fatal: '', net: '', app: '', seq: '' },
  options: {
    appenders: {
      out: { type: 'console', maxLogSize: 10000000, backups: 10 },
      seq: { type: 'file', maxLogSize: 1000000000, backups: 10 },
      main: {
        type: 'dateFile',
        pattern: 'yyyy-MM-dd-hh',
        keepFileExt: true,
        maxLogSize: 10000000,
        backups: 10,
        numBackups: 24,
        compress: false,
        alwaysIncludePattern: false,
      },
      app: {
        type: 'dateFile',
        pattern: 'yyyy-MM-dd-hh',
        keepFileExt: true,
        maxLogSize: 10000000,
        backups: 10,
        numBackups: 24,
        compress: false,
        alwaysIncludePattern: false,
      },
      p2p: {
        type: 'dateFile',
        pattern: 'yyyy-MM-dd-hh',
        keepFileExt: true,
        maxLogSize: 10000000,
        backups: 10,
        numBackups: 24,
        compress: false,
        alwaysIncludePattern: false,
      },
      snapshot: { type: 'file', maxLogSize: 10000000, backups: 10 },
      cycle: { type: 'file', maxLogSize: 10000000, backups: 10 },
      fatal: { type: 'file', maxLogSize: 10000000, backups: 10 },
      exit: { type: 'file', maxLogSize: 10000000, backups: 10 },
      errorFile: { type: 'file', maxLogSize: 10000000, backups: 10 },
      errors: { type: 'logLevelFilter', level: 'ERROR', appender: 'errorFile' },
      net: { type: 'file', maxLogSize: 10000000, backups: 10 },
      playback: { type: 'file', maxLogSize: 10000000, backups: 10 },
      shardDump: { type: 'file', maxLogSize: 10000000, backups: 10 },
      statsDump: { type: 'file', maxLogSize: 10000000, backups: 10 },
    },
    categories: {
      default: { appenders: ['out'], level: 'trace' },
      app: { appenders: ['app', 'errors'], level: 'trace' },
      main: { appenders: ['main', 'errors'], level: 'trace' },
      seq: { appenders: ['seq'], level: 'trace' },
      p2p: { appenders: ['p2p'], level: 'trace' },
      snapshot: { appenders: ['snapshot'], level: 'trace' },
      cycle: { appenders: ['cycle'], level: 'trace' },
      fatal: { appenders: ['fatal'], level: 'fatal' },
      exit: { appenders: ['exit'], level: 'fatal' },
      net: { appenders: ['net'], level: 'trace' },
      playback: { appenders: ['playback'], level: 'trace' },
      shardDump: { appenders: ['shardDump'], level: 'trace' },
      statsDump: { appenders: ['statsDump'], level: 'trace' },
    },
  },
}

export default LOGS_CONFIG
